services:

  db:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: weatherapi
    volumes:
      - ./.db:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      HOST: 0.0.0.0
      DB_URL: postgresql://user:pass@db:5432/weatherapi
    depends_on:
      - db
